version: '3.8'
services:
  etalik_app:
    depends_on:
      - etalik_db
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
    working_dir: /var/www/html
    container_name: etalik_app
    ports:
      - "8888:80"
    extra_hosts:
      - host.docker.internal:host-gateway
    volumes:
      - ./docker/vhosts:/etc/apache2/sites-enabled
      - .:/var/www/html
      - ./docker/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./docker/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
      - ./docker/xdebug.log:/var/www/xdebug.log
    restart: always

  ###> doctrine/doctrine-bundle ###
  etalik_db:
    image: 'mariadb:10.5'
    container_name: etalik_db
    restart: always
    environment:
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'root'
      MYSQL_DATABASE: 'test'
      MYSQL_ROOT_PASSWORD: 'root'
    volumes:
      - etalik_db-db-data:/var/lib/mysql/
    ports:
      - '3312:3306'

###< doctrine/doctrine-bundle ###

volumes:
  etalik_db-db-data:
